[package]
name = "ps-base64"
version = "0.1.0-8"
edition = "2021"
rust-version = "1.87"
description = "Base64 encode/decode"
repository = "https://github.com/prokopschield/ps-base64"
license = "GPL-3.0-or-later"
keywords = ["base64", "base64url", "decode", "encode"]
categories = ["encoding"]

[lints.clippy]
expect_used = "warn"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
